// types/index.ts

export interface MenuItem {
  id:          string;
  name:        string;
  category:    'main' | 'addon';
  hasSizes:    boolean;
  prices: {
    S?:        number;
    M?:        number;
    L?:        number;
    fixed?:    number;
  };
  available:   boolean;
  sortOrder:   number;
  description?: string;
  imageUrl?:    string;
}

export interface AddOn {
  menuItemId:  string;
  name:        string;
  price:       number;
}

export interface BundleItem {
  cartItemId:  string;          // uuid — generated by reducer via crypto.randomUUID()
  menuItemId:  string;
  name:        string;
  size:        'S' | 'M' | 'L';
  basePrice:   number;
  addons:      AddOn[];         // 0 or more, never standalone
  bundleTotal: number;          // basePrice + sum(addon.price)
  quantity:    number;          // number of this bundle ordered
}

export interface Order {
  id:            string;
  orderNumber:   number;
  items:         BundleItem[];
  total:         number;
  paymentMethod: 'cash' | 'momo' | 'card';
  status:        'completed' | 'cancelled' | 'pending';
  paystackRef?:  string;        // Phase 2
  platformFee?:  number;        // Phase 2 — 1% cut
  vendorAmount?: number;        // Phase 2 — total minus 1%
  createdAt:     string;
}

export interface AppSettings {
  businessName:      string;
  adminPIN:          string;
  nextOrderNumber:   number;
  paystackPublicKey?: string;   // Phase 2
  platformFeePct?:   number;    // Phase 2 — default 0.01 (1%)
}

export interface CashierUser {
  id: string;
  name: string;
  role: 'cashier' | 'admin';
  emailOrPhone: string;
  passwordHash: string; // Plaintext for mock phase, encrypted on Supabase
  createdAt: string;
}

export interface StoreSettings {
  isOpen: boolean;
  deliveryFee: number;
  taxRate: number; // percentage
}

export interface AppState {
  menu:          MenuItem[];
  addons:        MenuItem[];      // filtered: category === 'addon'
  orders:        Order[];
  cart:          BundleItem[];    // session only, never persisted
  currentOrder:  Order | null;
  paymentMethod: 'cash' | 'momo'; // Phase 2 adds 'card'
  adminUnlocked: boolean;
  currentUser:   CashierUser | null;
  staff:         CashierUser[];
  // START_BUNDLE stores the in-progress main + size here;
  // AddonSheet reads this to know what to display.
  pendingBundle: { menuItemId: string; size: 'S' | 'M' | 'L'; customPrice?: number; cartItemId?: string } | null;
  storeSettings: StoreSettings;
}

